# Generated by Django 3.0.7 on 2020-09-18 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('team_name', models.CharField(max_length=50)),
            ],
        ),
    ]
