# Generated by Django 3.0.7 on 2020-11-25 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecl', '0002_auto_20201004_1439'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='status',
            field=models.CharField(default='inactive', max_length=20),
        ),
    ]
