# Generated by Django 3.0.7 on 2020-11-25 13:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ecl', '0003_tournament_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdetails',
            name='team_selected',
            field=models.ForeignKey(default='N', on_delete=django.db.models.deletion.CASCADE, related_name='team_selected', to='ecl.Team'),
        ),
    ]
